DEFAULT_BRANCH: master

ENABLE_LINTERS:
  - DOCKERFILE_HADOLINT
  - JSON_PRETTIER
  - YAML_PRETTIER

YAML_PRETTIER_FILTER_REGEX_EXCLUDE: .github/*
JSON_PRETTIER_FILTER_REGEX_EXCLUDE: .github/*

SHOW_ELAPSED_TIME: true
FILEIO_REPORTER: false
PRINT_ALPACA: false
