trigger:
  branches:
    include:
      - master
      - develop

pr:
  - master
  - develop

pool:
  vmImage: "ubuntu-latest"

name: PaymentHub_$(Date:yyyyMMdd)$(Rev:.r)

steps:

  - script: |
      # Lint
      helm dependency update helm/oaf
      helm lint helm/oaf
    displayName: Helm lint

  - task: HelmDeploy@0
    displayName: Package Helm Chart
    inputs:
      command: package
      chartPath: $(System.DefaultWorkingDirectory)/helm/oaf
      destination: $(Build.ArtifactStagingDirectory)
      updatedependency: false

  - task: PublishBuildArtifacts@1
    displayName: Publish Helm chart
    # Only publish develop branch
    # condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
    inputs:
      PathtoPublish: "$(Build.ArtifactStagingDirectory)"
      ArtifactName: "paymenthub"
      publishLocation: "Container"