name: Lint with Mega-linter

on:
  push:
    branches-ignore:
      - quality-checks
  pull_request:
    branches:
      - main
      - develop
      - master

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0

      - name: Mega-Linter
        uses: oxsecurity/megalinter/flavors/ci_light@v6.9.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}